export type IcebreakerCategory = 'Introductions' | 'Icebreakers' | 'Advice' | 'Resume' | 'Portfolio'

export const ICEBREAKER_CONTENT: Record<IcebreakerCategory, string[]> = {
  Advice: [
    "Research each company’s values and key goals before attending.",
    "Prepare questions for recruiters about company culture, design teams, and interview process.",
    "Update your LinkedIn with descriptions of your experiences and a professional headshot (a nice picture makes a big difference!)",
    "Dress to impress. We recommend coming in business casual attire.",
    "Take notes after each conversation to remember recruiter names, feedback, and next steps.",
    "Follow up with personalized thank-you emails within 24 hours referencing details from your conversation.",
    "Don’t rush conversations — quality over quantity.",
    "Practice self-care. Eat, hydrate, and sleep before the big day.",
    "Network with fellow student designers! STRIDE is a great way to get to know your peers, not just companies.",
    "On the LinkedIn app, tap the search bar and use your profile QR code on the top right for easy sharing!",
    "When talking about your experience, consider the STAR method: situation, task, action, and result.",
    "Keep a folder with a few copies of your physical resume to hand to companies.",
    "Lead with curiosity, not self-promotion. Ask genuine questions to get to know the recruiter, company, and their design process.",
    "Treat every conversation as a two-way interview; you’re also assessing if they align with your values.",
    "Maintain strong body language: upright posture, steady eye contact, and a relaxed smile go a long way.",
    "Turn nerves into curiosity. Shift “I hope they like me” into “I’m excited to learn what they do.”",
    "Treat every interaction as practice. Even if you don’t land a job, you’re gaining connections and improving your communication skills.",
    "Check the agenda at stride25.designatucsd.com to plan which company sessions you’re attending.",
    "Have your digital portfolio easily accessible on your phone or laptop to show.",
    "Reflect and define your value proposition. Why would someone want to hire you?",
  ],
  Icebreakers: [
    "Ask about the recruiter’s favorite recent project—it’s an easy way to spark conversation.",
    "Bring up how their company encourages innovation and collaboration. It’s a great way to learn more about their culture.",
    "What surprised you about your company or role when you first started? Get to know the recruiter and their experience more.",
    "What made you choose your company?",
    "How does your company stay inspired with new ideas considering changing technologies and environments?",
    "How has being at your company helped you grow within the design industry?",
    "What tools or softwares does the company use in their projects?",
    "What’s a piece of advice you’d give to someone interested in exploring the design industry?",
    "How does your company navigate challenges, especially when working across cross-functional teams?",
    "What is your favorite company tradition?",
    "What does the learning curve look like for an intern in your company?",
    "What’s the best piece of advice you’ve received throughout your career?",
    "What’s a hobby you have outside work that helps you in your professional career?",
    "What growth opportunities does your company offer?",
    "What skills or projects make student candidates stand out most right now?",
    "What’s one thing you’re excited about achieving as a company in the near future?",
    "If your company were a city, what city would it be?",
    "How does your company take initiative to support employee well-being?",
    "How does your company implement culture into the workplace?",
    "If you had to recommend any resource (book, blog, movie, podcast) to understand your industry better, what would it be?",
  ],
  Introductions: [
    "Start with your name, major, and what kind of design work you focus on. Keep it simple and clear.",
    "Lead with what excites you most about design. Passion is memorable!",
    "Mention one project or experience that highlights your strengths or interests.",
    "Keep your pitch brief. Recruiters meet many people, so be considerate!",
    "Practice saying your introduction out loud until it sounds natural, not rehearsed.",
    "Share what kind of roles or opportunities you’re looking for (e.g. “I’m looking for a UX design internship focused on accessibility”).",
    "Use plain language. Skip the jargon and make your story relatable.",
    "End with a question that keeps the conversation going, like “How does your team approach user research?”",
    "Include something memorable. A quirky fact, niche interest, or personal design philosophy.",
    "Practice introducing yourself to friends beforehand and ask for feedback on clarity.",
    "Record yourself and listen for pacing. You want to sound relaxed, not rushed.",
    "Avoid reading off a script. Preparing bullet points in your head is enough.",
    "If you get nervous, take a breath and smile before starting; it helps reset your tone.",
    "End conversations with gratitude and enthusiasm.",
    "Tailor your intro to connect with the company’s focus. Mention what specifically draws you to their work or values.",
    "Keep your body language open. Stand tall, relax your shoulders, and gesture naturally as you speak.",
    "If you stumble, smile and keep going. Authenticity matters more than perfection.",
    "Think of your introduction as an invitation, not a performance. You’re starting a conversation, not delivering a speech.",
    "End with a clear next steps. Offer your contact info, ask about open roles, or express interest in staying connected.",
  ],
  Resume: [
    "Bring a few physical copies of your resume to hand to recruiters.",
    "Keep your resume to one page.",
    "Make sure your resume is ATS friendly. You can use tools such as Overleaf to format them.",
    "Avoid using too many colors; keep it simple and professional.",
    "Put your most relevant experiences at the top.",
    "Quantify your impact with metrics in each of your experiences.",
    "Include 3–5 bullet points under each experience. Keep each point impactful yet concise.",
    "Include your email, phone number, LinkedIn, and portfolio URL at the top of the page.",
    "Include any college-level design coursework you’ve taken.",
    "Include any awards (such as design-a-thons and hackathons).",
    "If you don’t have previous internship experience, include project work and volunteer design experiences.",
    "Use verb-led phrases, such as “improved,” “implemented,” “optimized.”",
    "List relevant design skills, such as wireframing, prototyping, testing, and research.",
    "List relevant design tools, such as Figma, Adobe, or Sketch.",
    "List soft skills that demonstrate collaboration and leadership.",
    "Proofread multiple times — typos hurt credibility.",
    "Name your file professionally: Firstname_Lastname_Resume.pdf.",
    "Tailor your resume to the job title you want.",
    "Demonstrate your ability to collaborate cross-functionally with teams.",
    "Ask a mentor or career advisor to critique it.",
  ],
  Portfolio: [
    "Include metrics to quantify your impact on each project.",
    "Define your role in team projects clearly.",
    "In each case study, include the project timeline, who you worked with, and what tools you used.",
    "For each case study, show your process: problem, research, ideation, iterations, and final prototypes.",
    "Make sure your website is responsive on desktop and mobile.",
    "Keep each case study scannable and engaging. Recruiters won’t spend longer than a few minutes reviewing your portfolio.",
    "Curate your portfolio. Lead with 2–4 of your strongest, most relevant projects.",
    "Rehearse a 2–3 minute walkthrough for each project.",
    "Show, don’t tell — include sketches, prototypes, and early iterations that informed your final solution.",
    "Emphasize storytelling — each project should have a clear problem and solution.",
    "Use clear captions that describe context and outcomes. Avoid long paragraphs of text.",
    "Ask peers or mentors to review your portfolio and give feedback.",
    "Add an “About” page that highlights your story, design motivation, and key details employers should know — plus an easy way to reach you.",
    "Link your LinkedIn and resume in your portfolio.",
    "Use website builders such as Framer, Webflow, or Squarespace to showcase your work. Or, if you have the time, code your own!",
    "Frame your passion projects, volunteer work, and class projects as relevant design experiences.",
    "Make a custom URL and include it in your resume and LinkedIn profile.",
    "Keep refining — your portfolio is always evolving.",
    "Use consistent image sizes and formatting.",
    "Include animations, GIFs, and video content to make your website more engaging.",
  ],
}


